### ISSUE TITLE
Encoding structs with nil values

### ISSUE THREAD

**Issue by lucacorti** [devinus/poison#57] opened 2016-01-14 18:07 UTC
I have a struct which and I do not want keys to be included in the encoded payload when the associated value is `nil`. Is this possible? Maybe there should be an option for this?

**Comment by edgurgel** [comment] 2016-01-14 21:07
Possibly a duplicate of https://github.com/devinus/poison/issues/55

**Comment by devinus** [comment] 2016-06-21 09:51
Indeed, duplicate of #55.

**Closed by devinus** 2016-06-21 09:51 UTC
